# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '10.0'

target 'CalismaAlani_Deneme' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CalismaAlani_Deneme

  pod 'SwiftyJSON', '~> 4.0'
end
